package pers.zxt.springboot.ssm;

import org.springframework.boot.SpringBootConfiguration;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.servers.Server;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.Explode;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.enums.ParameterStyle;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * Springdoc 配置 Swagger 的第 2 种方式，使用注解，比较常用。
 * 此时使用的是 io.swagger.v3.oas.annotations 里提供的各个 **注解** 来构造 Swagger 所需要的信息。
 * 此种方式不需要使用 @SpringBootConfiguration 注解，因为 @OpenAPIDefinition 注解就足够让 SpringDoc 获取到配置了。
 * 并且似乎 注解的优先级 > Bean方式的优先级。
 * 默认访问URL: http://localhost:8081/swagger-ui/index.html
 */
//@SpringBootConfiguration
@OpenAPIDefinition(
    // API的基本信息，包括标题、版本号、描述、联系人等
    info = @Info(
        title = "Swagger3.0 (Open API) 框架",                               // Api接口文档标题（必填）
        description = "Some Description. **Generated by Annotation**.",    // Api接口文档描述
        version = "1.2.1",                                   // Api接口版本
        termsOfService = "https://example.com/",             // Api接口的服务条款地址
        contact = @Contact(                                // 设置联系人信息
            name = "DocAuthor",                            // 作者名称
            email = "example@email.com",                   // 作者邮箱
            url = "https://example.com/"                   // 介绍作者的URL地址
        ),
        license = @License(
            name = "Apache 2.0",                                       // 授权名称
            url = "https://www.apache.org/licenses/LICENSE-2.0.html"   // 授权信息
        )
    ),
    // 表示服务器地址或者URL模板列表，多个服务地址随时切换（只不过是有多台IP有当前的服务API）
    servers = {
        @Server(url = "http://192.168.2.235/demo/", description = "本地服务器一服务")
    },
    // 外部文档信息
    externalDocs = @ExternalDocumentation(description = "更多内容请查看该链接", url = "https://other.example.com/")
)
public class SwaggerOpenApiConfigAnno {
}
