server:
  port: 8100

logging:
  level:
#    root: DEBUG
    root: INFO

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: mysql2022
  redis:
    host: localhost
    port: 6379
    # password: yourpassword  # 如果有密码
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
